{
 "title": "Sensor Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"dev\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"opc_server\" and\n    r._field == \"Temperature\"\n  )"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"dev\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"opc_server\" and\n    r._field == \"Pressure\"\n  )"
    }
   ]
  },
  {
   "title": "SlowSensor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"dev\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"opc_server\" and\n    r._field == \"SlowSensor\"\n  )"
    }
   ]
  },
  {
   "title": "Model Computations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"dev\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"model\" and r._field == \"value\" and\n    r.name == \"model1\" or r.name == \"model2\"\n  )"
    }
   ]
  }
 ]
}